### ISSUE TITLE
lucee-cfimap for idiots

### ISSUE THREAD

**Issue by lukecr** [Tropicalista/lucee-cfimap#18]
hi

i don't know if this is really the place for this, but i couldn't find an email address - but i was wondering how this works? after installing, does this replace the lucee cfimap tag? or is this called differently?

sorry for a probably a stupid question, but i've never had to install or use a tag (if it is a tag?!) like this before

does this have the same functionality as the adobe coldfusion tag? it seems to from your description

thanks

luke

**Comment by Tropicalista** [comment]
Hi,

- Save to Lucee context directory ("context/library/tag")
- you will need to restart Lucee when you have added these files (and after editing a tag)

After that you can use it as cfimap, this simply replace lucee cfimap which is a simple facade of the cfpop.

**Comment by lukecr** [comment]
thanks. so after install/restart - i use the <cfimap tag and it'll run your version instead?

**Comment by Tropicalista** [comment]
Yes
